spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flicktionary

#김형준
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/prod?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234